language: go

go:
  - 1.14.x
  - 1.15.x

services:
  - docker
  - redis-server
  
install:
  - docker pull grokzen/redis-cluster:6.0.0
  - docker run -e "IP=0.0.0.0" -d -p 7000-7005:7000-7005 --name redis-cluster grokzen/redis-cluster:6.0.0

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
