language: go

go:
  - 1.14.x
  - 1.15.x

services:
  - docker
  - redis-server
install:
  - docker pull grokzen/redis-cluster:6.0.0
  - docker run -d -p 7000:7000 -p 7001:7001 -p 7002:7002 -p 7003:7003 -p 7004:7004 -p 7005:7005 --name redis-cluster grokzen/redis-cluster:6.0.0

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
