[server]
  listen_address="0.0.0.0:8081" # websocket port
[[redis]]
  name="impress"
  address=["10.0.2.32:6379"]
  # password="viewer"
[log]
  # log_path="./tmp/"  # 日志存放目录,需人为创建好目录，不设置该值的时候，默认 stdout 进行日志输出
  log_level=["LOGERROR"] # LOGNONE 「禁止输出」 |  LOGERROR「错误级别日志」  |  LOGWARN「警告级别」  |  LOGDEBUG「debug 级别，该级别包含大量日志（含所有操作命令记录），谨慎使用」    默认 LOGERROR
[auth-config]
  key="F$&&*F*J)"
[[auth]]
  user="root"
  password="root"
  # dev | monit | exec
  permission=["dev","monit","exec"]  
[[auth]]
  user="viewer"
  password="viewer"
  # dev | monit | exec
  permission=[]  
[prometheus]
  path="/prometheus"

[opcap]
  device="en0"
  BPFFilter="host 10.0.6.29 and dst port 8080" # http://www.tcpdump.org/manpages/pcap-filter.7.html

